### ISSUE TITLE
Error on running the samples

### ISSUE THREAD

**Issue by nerezo** [CodeReclaimers/btce-bot#12]
Hi,

When I try to run one of the samples, the below error occurs:

```console
Traceback (most recent call last):
  File "hello-world-bot.py", line 8, in <module>
    import btcebot
  File "build/bdist.linux-x86_64/egg/btcebot/__init__.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/btcebot/bot.py", line 9, in <module>
ImportError: cannot import name validatePair
```

There is no **validatePair** implementation in the common.py file as I see and it wants to import that.

**Comment by CodeReclaimers** [comment]
I think you might be using the latest btce-api from GitHub--I've made some changes to that recently but haven't updated btce-bot to use it.

You should be able to use the current btce-bot with the btce-api installed from PyPI (https://pypi.python.org/pypi/btce-api/0.3), or from a revision before I started making changes (https://github.com/CodeReclaimers/btce-api/archive/6a6fa03ae47ad8f3f671e00d508bd1b3e03f8010.zip).

Let me know if you still have issues when using one of those.

**Comment by nerezo** [comment]
I am reading the "Getting Started" tutorial. I downloaded the files from the url that has been specified there.
Okay, let me try with those new urls.

Very thanks.
