### ISSUE TITLE
KeyHandler error

### ISSUE THREAD

**Issue by amazzuca** [CodeReclaimers/btce-bot#14]
I'm having the following error: 

Traceback (most recent call last):
  File "hello-world-bot.py", line 141, in <module>
    run(args.key_file, args.buy_floor, args.sell_ceiling, args.live_trades)
  File "hello-world-bot.py", line 93, in run
    key = handler.getKeys()[0]
AttributeError: 'KeyHandler' object has no attribute 'getKeys'

What could be the reason?

The command line was:

C:\Users\Alexander\nueva_api_btc\btce-bot-master\samples>python hello-world-bot.
py "C:\users\Alexander\nueva_api_btc\btce-bot-master\btce-keys.txt" 4.0 4.1

Thanks a lot

**Comment by T772929357** [comment]
same as you
